### ISSUE TITLE
--------

### ISSUE THREAD

**Issue by BerkanYildiz** [kylecourounis/BackBot#1]
![](https://media1.tenor.com/images/b5ff4d9783c61db83962f07155802827/tenor.gif?itemid=5637398)

**Comment by kylecourounis** [comment]
Never got around to saving the backups in JSON format (and now don't plan to) cuz like laziness 'n shiz lol

**Comment by BerkanYildiz** [comment]
[Models.zip](https://github.com/kyledoescode/BackBot/files/2949853/Models.zip)

**Comment by kylecourounis** [comment]
Cool, but like I still don't plan on updating it lol -- maybe eventually thanks lol

**Comment by BerkanYildiz** [comment]
You havn't changed, still a lazy motherfucker

**Comment by kylecourounis** [comment]
Meh
